<<<<<<< HEAD
// This file is auto-generated by scripts/sync-version.ts
export const GHOST_VERSION = "2.4.13";
export const BUILD_DATE = "2026-01-19T02:40:40.413Z";
=======
// Auto-generated by scripts/release.ts
import pkg from '../../package.json'
export const GHOST_VERSION = pkg.version
export const BUILD_DATE = '2026-01-10T08:32:54.303Z'
>>>>>>> 3c75ad6140cc308c7b1c587461fc22735e018656
