import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { zyLog } from '../src/lib/zylog'

const packageJsonPath = join(process.cwd(), 'package.json')
const cargoPath = join(process.cwd(), 'ghost-agent', 'Cargo.toml')
const versionTsPath = join(process.cwd(), 'src', 'lib', 'version.ts')

try {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
  const version = packageJson.version

  if (version) {
    // 1. Update src/lib/version.ts
    const tsContent = `// This file is auto-generated by scripts/sync-version.ts
export const APP_VERSION = "${version}";
export const GHOST_VERSION = "${version}";
export const BUILD_DATE = "${new Date().toISOString()}";
`
    writeFileSync(versionTsPath, tsContent)
    zyLog.success(`Frontend version synced: ${version}`)

    // 2. Update ghost-agent/Cargo.toml
    if (readFileSync(cargoPath, 'utf-8').includes(`version = "${version}"`)) {
      zyLog.info('Cargo.toml already in sync.')
    } else {
      const cargoContent = readFileSync(cargoPath, 'utf-8')
      const newCargoContent = cargoContent.replace(
        /version\s*=\s*"([^"]+)"/,
        `version = "${version}"`,
      )
      writeFileSync(cargoPath, newCargoContent)
      zyLog.success(`Cargo.toml version synced: ${version}`)
    }
  } else {
    zyLog.error('Could not find version in package.json')
  }
} catch (error) {
  zyLog.error('Error syncing version:', error)
}
