import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const cargoPath = join(process.cwd(), "ghost-agent", "Cargo.toml");
const versionTsPath = join(process.cwd(), "src", "lib", "version.ts");

try {
  const cargoContent = readFileSync(cargoPath, "utf-8");
  const versionMatch = cargoContent.match(/version\s*=\s*"([^"]+)"/);

  if (versionMatch && versionMatch[1]) {
    const version = versionMatch[1];
    const content = `// This file is auto-generated by scripts/sync-version.ts
export const GHOST_VERSION = "${version}";
export const BUILD_DATE = "${new Date().toISOString()}";
`;
    writeFileSync(versionTsPath, content);
    console.log(`✅ Version synced: ${version}`);
  } else {
    console.error("❌ Could not find version in Cargo.toml");
  }
} catch (error) {
  console.error("❌ Error syncing version:", error);
}
